springdoc:
  swagger-ui:
    path: /docs
server:
  port: 9002
spring:
  application:
    name: booking-service
  r2dbc:
    username: myuser
    password: secret
    url: r2dbc:postgresql://localhost:5432/airlinedb_booking
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      client-id: ${spring.application.name}
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: ${spring.application.name}


ticket:
  catalog-flight-uri: "http://localhost:9001"
message:
  topic: